In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('my_dataset.csv')
df

,Age,Income,Credit_Score,Loan_Amount,Loan_Term,Interest_Rate,Monthly_Installment,Debt_to_Income_Ratio,Employment_Length,Savings_Amount,...,Exercise_Hours_Per_Week,Caloric_Intake,Sleep_Hours,Social_Media_Usage,Streaming_Subscriptions,Gaming_Hours,Work_Hours_Per_Week,Default_Status,Churn_Status,Future_Spending
0,56,29930,839,401314,48,9.125587,506,0.449891,5,284603,...,7.753539,2996,9.643717,9,1,7.607873,70,0,0,1062.265348
1,69,23285,811,32020,48,4.191150,1561,0.314764,3,353300,...,4.149309,3064,9.825020,0,1,5.722815,28,0,0,1642.302963
2,46,143637,510,455488,72,4.277766,1874,0.126116,2,161992,...,1.360163,2152,5.126946,2,4,16.747437,75,0,0,1194.021867
3,32,55863,552,127043,48,9.300053,1470,0.164474,5,447093,...,6.975082,3769,9.524832,3,1,5.450359,56,0,0,2099.157592
4,60,36704,337,449555,60,1.612464,585,0.479467,14,479035,...,2.649262,1644,7.699206,7,1,2.545616,40,1,0,2541.693245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,55,23333,702,36455,36,2.802468,522,0.392726,3,150261,...,8.895799,2271,7.677734,4,1,14.292045,47,0,0,1329.400826
9996,51,60002,630,231420,72,2.918479,1217,0.146876,20,99047,...,0.916842,2647,7.538399,8,2,14.407259,10,0,0,1643.928613
9997,57,144477,756,333704,72,8.274231,4738,0.127861,5,16918,...,6.289089,3441,8.728525,9,1,3.271238,46,0,0,4545.900477
9998,64,83620,782,358908,12,7.475442,4950,0.348762,1,325631,...,9.132855,2343,7.514801,6,0,13.776673,54,0,0,4608.444078
9999,32,107688,797,152993,36,5.805488,4071,0.475459,36,467266,...,5.893241,2061,9.664183,9,2,0.976641,40,0,0,2763.278808